FROM golang:1.25-alpine

WORKDIR /app

# important: fix networking + git deps
RUN apk add --no-cache git ca-certificates

RUN go install github.com/air-verse/air@latest

# 🔥 FIX: avoid proxy.golang.org issues
ENV GOPROXY=direct
ENV GOSUMDB=off

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]