FROM golang:1.22-alpine



WORKDIR /app

# important: fix networking + git deps
RUN apk add --no-cache git ca-certificates

ENV GOTOOLCHAIN=auto
ENV GOPROXY=https://proxy.golang.org,direct
ENV GOSUMDB=off

RUN go install github.com/air-verse/air@latest



COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]