import { useParams, useNavigate } from '@tanstack/react-router'
import { useQuery } from '@tanstack/react-query'
import { ArrowLeft } from 'lucide-react'

import { AppShell } from '@components/layout'
import { Banner, Card, CardContent, EmptyState, Spinner, Tabs, TabsContent, TabsList, TabsTrigger } from '@components/ui'
import { getStudentSkillStates } from '@lib/api/endpoints'
import { queryKeys } from '@lib/query/keys'
import { cn } from '@lib/utils/cn'
import type { SkillState } from '@/types/api'

const MASTERY_COLORS: Record<string, string> = {
  mastered: 'text-health-700 bg-health-50 border-health-200',
  proficient: 'text-health-600 bg-health-50 border-health-100',
  emerging: 'text-seal-700 bg-seal-50 border-seal-200',
  at_risk: 'text-alert-700 bg-alert-50 border-alert-200',
  unknown: 'text-gray-500 bg-gray-50 border-gray-200',
}

export function TeacherStudentDetailPage() {
  const navigate = useNavigate()
  // studentId comes from the URL param
  const { studentId } = useParams({ from: '/teacher/students/$studentId' })

  // GET /students/{id}/skill-states -- server-side ownership check
  // (Service.SkillStatesForStudent / authorizeExplain) enforces the
  // caller may only view a student at their own school.
  const { data, isLoading, isError } = useQuery({
    queryKey: queryKeys.studentSkillStates(studentId),
    queryFn: () => getStudentSkillStates(studentId),
  })

  const skillStates = data?.skillStates ?? []

  return (
    <AppShell>
      <div className="space-y-6">
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate({ to: '/teacher/students' })}
            aria-label="Back to student roster"
            className="rounded p-1 text-gray-400 hover:text-gray-700 focus:outline-none focus:ring-2 focus:ring-primary-500"
          >
            <ArrowLeft className="h-5 w-5" aria-hidden />
          </button>
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Student Detail</h1>
            <p className="mt-0.5 text-sm text-gray-500">
              ID: <span className="font-mono">{studentId}</span>
            </p>
          </div>
        </div>

        {isError && (
          <Banner tone="error" title="Failed to load student data" description="Try refreshing." />
        )}

        <Tabs defaultValue="skill-states">
          <TabsList>
            <TabsTrigger value="skill-states">Skill States</TabsTrigger>
            <TabsTrigger value="misconceptions">Misconceptions</TabsTrigger>
          </TabsList>

          <TabsContent value="skill-states" className="mt-4">
            {isLoading ? (
              <div className="flex justify-center py-12">
                <Spinner />
              </div>
            ) : skillStates.length === 0 ? (
              <EmptyState
                title="No skill states recorded"
                description="This student has not completed any graded exams yet."
              />
            ) : (
              <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                {skillStates.map((state) => (
                  <SkillCard
                    key={state.topicId}
                    state={state}
                    studentId={studentId}
                    onExplain={() =>
                      navigate({
                        to: '/students/$studentId/topics/$topicId/explain',
                        params: { studentId, topicId: state.topicId },
                      })
                    }
                  />
                ))}
              </div>
            )}
          </TabsContent>

          <TabsContent value="misconceptions" className="mt-4">
            <Card>
              <CardContent className="py-8 text-center text-sm text-gray-400">
                Misconception hypotheses for this student will appear here once generated by the AI.
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </AppShell>
  )
}

function SkillCard({
  state,
  onExplain,
}: {
  state: SkillState
  studentId: string
  onExplain: () => void
}) {
  const colorClass = MASTERY_COLORS[state.masteryStatus] ?? MASTERY_COLORS.unknown
  const pct = state.masteryProbability != null ? Math.round(state.masteryProbability * 100) : null

  return (
    <Card className="flex flex-col">
      <CardContent className="flex flex-1 flex-col gap-3 py-4">
        <div className="flex items-start justify-between gap-2">
          <p className="text-sm font-medium leading-snug text-gray-900">{state.topicTitle}</p>
          <span className={cn('shrink-0 rounded-full border px-2 py-0.5 text-xs font-medium capitalize', colorClass)}>
            {state.masteryStatus.replace('_', ' ')}
          </span>
        </div>
        {pct !== null && (
          <div>
            <div className="h-1.5 w-full overflow-hidden rounded-full bg-gray-100">
              <div
                className={cn(
                  'h-full rounded-full',
                  pct >= 75 ? 'bg-health-500' : pct >= 50 ? 'bg-seal-500' : 'bg-alert-500',
                )}
                style={{ width: `${pct}%` }}
              />
            </div>
            <p className="mt-1 text-right text-xs text-gray-400">{pct}%</p>
          </div>
        )}
        <button
          onClick={onExplain}
          className="mt-auto self-start rounded-lg border border-primary-200 px-3 py-1 text-xs font-medium text-primary-700 hover:bg-primary-50 focus:outline-none focus:ring-2 focus:ring-primary-500"
        >
          Explain this topic
        </button>
      </CardContent>
    </Card>
  )
}
