export const queryKeys = {
  curriculumJob: (jobId: string) => ['curriculum', 'job', jobId] as const,
  curriculumJobs: (page: number) => ['curriculum', 'jobs', page] as const,
  curriculumTopics: (subjectCode: string) => ['curriculum', 'subjects', subjectCode, 'topics'] as const,
  topicPrerequisites: (topicId: string) => ['curriculum', 'topics', topicId, 'prerequisites'] as const,
  subjectVersions: (subjectCode: string) => ['curriculum', 'subjects', subjectCode, 'versions'] as const,
  subjectGraph: (subjectCode: string, includeClos: boolean) =>
    ['curriculum', 'subjects', subjectCode, 'graph', includeClos] as const,
  exam: (examId: string) => ['assessment', 'exam', examId] as const,
  examQuestions: (examId: string) => ['assessment', 'exam', examId, 'questions'] as const,
  gradingQuestions: (examId: string) => ['assessment', 'exam', examId, 'grading-questions'] as const,
  examQuality: (examId: string) => ['assessment', 'exam', examId, 'quality'] as const,
  examInsights: (examId: string) => ['assessment', 'exam', examId, 'insights'] as const,
  myExamInsight: (examId: string) => ['assessment', 'exam', examId, 'my-insight'] as const,
  students: (schoolId: string) => ['students', schoolId] as const,
  mySubjectProfiles: () => ['students', 'me', 'subject-profiles'] as const,
  myStudyPlans: () => ['students', 'me', 'study-plans'] as const,
  careerMatches: (studentId: string) => ['career', 'matches', studentId] as const,
  careerPaths: () => ['career', 'paths'] as const,
  classHeatmap: (subjectCode: string, gradeLevel: number) =>
    ['teachers', 'me', 'class-heatmap', subjectCode, gradeLevel] as const,
  schoolQuality: (schoolId: string) => ['schools', schoolId, 'quality-scores'] as const,
  ministryOverview: () => ['ministry', 'overview'] as const,
  regionStats: (regionId: string) => ['ministry', 'regions', regionId, 'stats'] as const,
  regions: () => ['regions'] as const,
  schools: (regionId?: string) => ['schools', { regionId }] as const,
  school: (schoolId: string) => ['schools', schoolId] as const,
  teachers: (schoolId: string) => ['teachers', schoolId] as const,
  notifications: () => ['notifications'] as const,
}
