-- EG-GCKT Milestone 6: structured misconception modeling (spec section
-- 11). The original gap-analysis pipeline only ever produced free-text
-- LLM explanations -- "misconception" as a concept never existed
-- anywhere in this codebase (confirmed by a full-repo grep during
-- planning). This table gives misconceptions the same structured
-- hypothesis shape the spec's field table describes: a candidate claim,
-- linked evidence, a confidence score, a verification item, and an
-- explicit candidate/confirmed/rejected lifecycle -- not just prose in an
-- exam_insights.llm_exam_summary string.

CREATE TABLE students.misconception_hypotheses (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id            UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    school_id             UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    topic_id              UUID NOT NULL REFERENCES curriculum.topics(id) ON DELETE CASCADE,
    misconception_text    TEXT NOT NULL,
    trigger_pattern        TEXT,
    supporting_evidence     JSONB,
    confidence               NUMERIC CHECK (confidence BETWEEN 0 AND 1),
    verification_item_id     UUID REFERENCES assessment.questions(id),
    status                    TEXT NOT NULL DEFAULT 'candidate' CHECK (status IN ('candidate', 'confirmed', 'rejected')),
    intervention_text          TEXT,
    generated_by_model           TEXT,
    reviewed_by                    UUID REFERENCES users(id),
    reviewed_at                     TIMESTAMPTZ,
    created_at                       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_misconception_hypotheses_student ON students.misconception_hypotheses(student_id, topic_id);
CREATE INDEX idx_misconception_hypotheses_status ON students.misconception_hypotheses(status) WHERE status = 'candidate';

-- Generated by an AI worker that can run locally at a School Box (same as
-- gap_records/skill_states), so it needs the same offline-sync outbox
-- coverage V029/V040 established for that class of table.
CREATE TRIGGER trg_outbox_misconception_hypotheses
    AFTER INSERT OR UPDATE OR DELETE ON students.misconception_hypotheses
    FOR EACH ROW EXECUTE FUNCTION sync.record_outbox_change('students.misconception_hypotheses');
